{
 "title": "Quote Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Application Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Health Status",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "app_health_status{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Application Uptime [sec]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "app_uptime_seconds{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage [%]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_cpu_usage_percent{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage [%]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_memory_usage_percent{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage [MB]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "app_memory_usage_mb{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "app_cpu_usage_percent{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "app_memory_usage_percent{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "app_request_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Error Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "app_error_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Successfull Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "app_successful_requests_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(app_request_count_total{instance=\"dc-quote-app:5000\"}[10m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(app_error_count_total{instance=\"dc-quote-app:5000\"}[10m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(app_successful_requests_total{instance=\"dc-quote-app:5000\"}[10m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate over Time [%]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "($A / $B) * 100", "type": "math" }
     ]
    },
    {
     "title": "Success Rate over Time [%]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "($A / $B) * 100", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Quotes Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Displayed Quotes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "app_total_quotes_displayed_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quotes Rate over Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "app_total_quotes_displayed_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quotes Distribution",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quote_1_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 1"
      },
      {
       "expr": "quote_2_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 2"
      },
      {
       "expr": "quote_3_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 3"
      },
      {
       "expr": "quote_4_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 4"
      },
      {
       "expr": "quote_5_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 5"
      },
      {
       "expr": "quote_6_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 6"
      },
      {
       "expr": "quote_7_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 7"
      },
      {
       "expr": "quote_8_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 8"
      },
      {
       "expr": "quote_9_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 9"
      },
      {
       "expr": "quote_10_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 10"
      },
      {
       "expr": "quote_11_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 11"
      },
      {
       "expr": "quote_12_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 12"
      },
      {
       "expr": "quote_13_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 13"
      },
      {
       "expr": "quote_14_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 14"
      },
      {
       "expr": "quote_15_count_total{instance=\"dc-quote-app:5000\"}",
       "legendFormat": "Quote 15"
      }
     ]
    }
   ]
  }
 ]
}